export {
  getAllSkills,
  getAllSkillsPaginated,
  getSkillDetails,
  getRelatedSkills,
  getSkillTrendingData,
  getSkillsWithFilters,
  getTrendingSkillsData,
  getHighPayingSkills,
  getEmergingSkills,
  getSkillGrowthStats,
  getSkillTimeline,
  getCategoryDistribution,
  getSkillsAdvancedStats,
  getRelatedSkillsEnhanced,
} from "./shared";
